version: "3.8"

services:
  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8001:8000
    restart: always
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres
    ports:
      - 5433:5432
    restart: always
    env_file:
      - .env
